version: "3"
services:
  #  payara:
  #    build: ../images/payara
  #    environment:
  #      - ADMIN_PASSWORD=adminadmin
  #    ports:
  #      - "8080:8080"
  #      - "4848:4848"

  db:
    image: mysql
    container_name: db_user
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: lab3_amt_user
      MYSQL_USER: adm
      MYSQL_PASSWORD: adm
      MYSQL_ROOT_PASSWORD: adminpw
    ports:
      - "3306:3306"

  db2:
    image: mysql
    container_name: db_vehicle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: lab3_amt_vehicle
      MYSQL_USER: adm
      MYSQL_PASSWORD: adm
      MYSQL_ROOT_PASSWORD: adminpw
    ports:
      - "3307:3306"
