openapi: '3.0.3'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
tags:
  - name: quotes-end-point
    description: Gestion des quotes
paths:
  /stations:
    get:
      tags:
        - quotes-end-point
      description: Liste toutes les quotes
      operationId: listStationsUsingGET
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Station'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
components:
  schemas:
    Station:
      type: object
      properties:
        address:
          type: string
      title: Station
