version: "3"
services:
  #payara:
  #  build: ../images/payara
  #  environment:
  #    - ADMIN_PASSWORD=adminadmin
  #  ports:
  #    - "8080:8080"
  #    - "4848:4848"

  db:
    build: ../images/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: lab1_AMT
      MYSQL_USER: adm
      MYSQL_PASSWORD: adm
      MYSQL_ROOT_PASSWORD: adminpw
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=adminpw
    ports:
      - "6060:80"
    links:
      - db:db
